from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<str:email>/', views.reset_password, name='reset_password'),
    path('logout/', views.user_logout, name='logout'),
    path('add-to-cart/<int:pid>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('increase/<int:cid>/', views.increase_qty, name='increase_qty'),
    path('decrease/<int:cid>/', views.decrease_qty, name='decrease_qty'),
    path('remove/<int:cid>/', views.remove_item, name='remove_item'),
    path('product/<int:pid>/', views.product_detail, name='product_detail'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add-to-wishlist/<int:pid>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-wishlist/<int:wid>/', views.remove_from_wishlist, name='remove_wishlist'),
    path('place-order/', views.place_order, name='place_order'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-success/', views.order_success, name='order_success'),
    path('add-category/', views.add_category,name='add_category'),
    path('display-category', views.display_category, name='display_category'),
    path('delete-category/<int:id>', views.delete_category, name='delete_category'),
    path('edit-category/<int:id>/', views.edit_category, name='edit_category'),
    path('add-product/', views.add_product,name='add_product'),
    path('display-product/', views.display_product, name='display_product'),
    path('delete-product/<int:id>', views.delete_product, name='delete_product'),
    path('edit-product/<int:id>/', views.edit_product, name='edit_product'),
    path('contact/', views.contact, name='contact'),
    path('invoice/<int:order_id>/', views.invoice, name='invoice'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('search/', views.search, name='search'),
    path('category/<int:cid>/',views.category_products,name='category_products'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('apply-coupon/',views.apply_coupon,name='apply_coupon'),
]