# Generated by Django 6.0.5 on 2026-05-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart', '0005_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
