# Generated by Django 6.0.5 on 2026-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart', '0008_remove_order_total_alter_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
